name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-1 
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        npm install
        
    - name: Build
      run: |
        npm run build
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::730335601824:role/git-cicd-role
        role-session-name: GithubActionsSession
        aws-region: us-east-1
        
    - name: Verify AWS credentials
      run: |
        aws sts get-caller-identity
        
    - name: Deploy to S3
      run: |
        aws s3 sync dist s3://${{ secrets.S3_BUCKET_NAME }}/products --delete
        
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*" 